### PR TITLE
Fixed displaying drop range (0 - 1) 

### PR DESCRIPTION
**Pull request by Benzeliden**
Example: Demon Horn in slot 2 for Demon Mage\Warrior. Currently shows 0 on site

### CODE REVIEW

**Comment by Phaturia** [comment]
Are you sure that this is okay? Now it's gonna say drop 0-1 for 100%. That's weird isn't it?
I'm sure the current one is wrong, but i think this isn't the best as well.

**Comment by Benzeliden** [comment]
Well technically it always 100% chance to receive drop from slot 2. But in this case you have 100% chance to receive from 0 to 1 Demon Horn.

Alternative fix could be: showing 1 instead of (0 - 1) but showing drop chance like 50%

**Comment by Phaturia** [comment]
How many quests there are which have this little paradox? If just some, then 0-1 | 100% is could be okay.

**Comment by Benzeliden** [comment]
I believe only 5 quests:
Demon Warrior
Demon Mage
Infernal Guardian
Phoenix
Cerberus

**Pull request merged**
