### PR TITLE
Reduce image size using OptiPNG and AdvanceCOMP:

### PR DESCRIPTION
**Pull request by fredrik-w**
- img/ went from 462394 bytes to 137137 bytes
- img/grades/ went from 6618 bytes to 5257 bytes

In total, filesize was reduced by 326618 bytes, or by roughly 70%.

### CODE REVIEW

**Comment by Dave-Hughes** [comment]
Awesome, thanks for this!

**Comment by Phaturia** [comment]
With this can we reduce assets folder too? Or those images are good?

**Comment by fredrik-w** [comment]
Well, as they reside as a zip-file in the repo I didn't touch them.

@Dave-Hughes would that be welcome? If so, I'll take care of it later today.

I can unzip, run optipng/advancecomp on them and then create a new zip-file if you'd like and make another pull request.

**Comment by Phaturia** [comment]
@fredrik-w The assets folder is directly from the apk, and if new version is come out then i upload the whole new folder, and overwrite everything. So if you just do it, then we lost every time a new version is out.

It would be more perfect if you could tell us how can we do it, then we can make an automate script, then just run at every release.

**Comment by fredrik-w** [comment]
I usually run:

``` bash
advpng -4 -z *.png
optipng -o7 *.png
advpng -4 -z *.png
```

The reason for the second invocation of advpng is that optipng will convert 24-bit images to 8-bit if it only uses less than 256 colours. This of course needs to be call from something that iterates over all directories.

**Comment by Phaturia** [comment]
Thank you sir!

**Comment by Phaturia** [comment]
@fredrik-w Oh WooW these tools are incredible :O
Just one thing: when i run advpng there is a lot of (Unsupported Interlace 1) "error". What is this?

Also what i noticed: the first advpng is very good its save 37% but the optipng is just 2% and the second advpng is just 1%. Anyway its an overall 40% saving. Very good, thanks.

**Comment by fredrik-w** [comment]
A bunch of the images are interlaced[1] for some reason, which advpng doesn't support. And apparently interlaced PNGs compress badly[2].

However, OptiPNG comes to the rescue as it supports both and can convert between progressive and interlaced.

```
       -i type
              Select the interlace type (0-1).
              If the interlace type 0 is selected, the output image  shall  be
              non-interlaced (i.e. progressive-scanned). If the interlace type
              1 is selected, the output image shall be  interlaced  using  the
              Adam7 method.
              By default, the output shall have the same interlace type as the
              input.
```

Now watch as magic happens when we tells OptiPNG to convert the image to a progressive one and then use advpng to compress it:

```
file ./assets/Weapons/Wand/Gnoll_Mystic_Wand.png
./assets/Weapons/Wand/Gnoll_Mystic_Wand.png: PNG image data, 24 x 24, 8-bit/color RGBA, interlaced

advpng -4 -z ./assets/Weapons/Wand/Gnoll_Mystic_Wand.png
       15192       15192 100% ./assets/Weapons/Wand/Gnoll_Mystic_Wand.png (Unsupported interlace 1)
       15192       15192 100%

optipng -o7 ./assets/Weapons/Wand/Gnoll_Mystic_Wand.png
[...]
Output IDAT size = 191 bytes (505 bytes decrease)
Output file size = 14776 bytes (416 bytes = 2.74% decrease)

 optipng -o7 -i0 ./assets/Weapons/Wand/Gnoll_Mystic_Wand.png
[...]
Output IDAT size = 128 bytes (63 bytes decrease)
Output file size = 14713 bytes (63 bytes = 0.43% decrease)

file ./assets/Weapons/Wand/Gnoll_Mystic_Wand.png
./assets/Weapons/Wand/Gnoll_Mystic_Wand.png: PNG image data, 24 x 24, 8-bit colormap, non-interlaced

 advpng -4 -z ./assets/Weapons/Wand/Gnoll_Mystic_Wand.png
       14713         272   1% ./assets/Weapons/Wand/Gnoll_Mystic_Wand.png
       14713         272   1%
```

Thus I would say, run OptiPNG with the `-i0` switch and cash in on big time filesize savings! :grin: 

[1] https://en.wikipedia.org/wiki/Interlacing_(bitmaps)
[2] https://en.wikipedia.org/wiki/Portable_Network_Graphics#Interlacing

**Comment by Phaturia** [comment]
So if i run 
optipng -o7 -i0 *.png
then
advpng -4 -z *.png
then it would be the easyest/verygood. Could be better, but then it's "harder" and much slower.

Thank you for all of this!

**Pull request merged**
